### ISSUE TITLE
Incompabilities with Inventorio

### ISSUE THREAD

**Issue by SireAwfulThe1st** [AstianBK/ChainMailed#3]
https://github.com/AstianBK/ChainMailed/assets/106896635/6e767f8c-f870-4470-b5d4-90ebd7de8ac9

It seems like the way your code redefine the player's sword attack method had caused some incompatibilities with Inventorio, being that sword items no longer works properly when put in Inventorio's toolbar. [something in this line of code had caused this](https://github.com/AstianBK/ChainMailed/blob/9b44c15d93371ad2a202a7ce24c4b36663025f06/src/main/java/com/TBK/chainmailed/common/mixins/PlayerMixin.java#L46-L209). So perhaps you may wanna look into it. RubixDev has said it's something regarding a bad code and nothing much that Inventorio could do with it.

**Comment by SangreBK** [comment]
That's from a leftover idea of making Chainmailed armor grant immunity to the damage from Sweeping Edge, that should've been deleted upon release, we'll remove that next update.

**Comment by SireAwfulThe1st** [comment]
> That's from a leftover idea of making Chainmailed armor grant immunity to the damage from Sweeping Edge, that should've been deleted upon release, we'll remove that next update.

Noted! glad the issue could be resolved, will be looking forward for the next update and the bugfix itself ^^.
